### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by erikkoli** [erikkoli/furima-39192#20]
【フリマアプリのURL】
https://furima-39192.onrender.com/

【Basic認証のIDとパスワード】
ID : admin
Pass : 2222

【出品者用のメールアドレスとパスワード】
Mail : test@com
Pass : asdfgh6

【購入者用のメールアドレスとパスワード】
Mail : admin@user
Pass : admin22

**Comment by motomuun** [comment]
@erikkoli さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
「ベビー・キッズ」のように、「・」で続く文字列は一つのカテゴリです。また、項目は全部で11項目となります。現在21項目表示されていますので、11項目となるように修正をお願いします。

- [ ] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
カテゴリーと同様です。「新品・未使用」は一つの項目です。現在8項目存在しますので、全部で7項目となるように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by erikkoli** [comment]
レビューありがとうございます！
修正いたしましたので、ご確認よろしくお願いいたします！
